Remove Impersonate access to Talk notifications
MetaProvide/adminly_notifications pull request #1
Opened 2022-10-07 15:19 UTC by oliveiraigorm

### Changes

Skips notifications from talk while a impersonate session is active.

### Testing

- Create a talk notification (by missing a call or sending a new message)
- If Log in as a provider you can see the notification
- If you log in as a VA and impersonate the provider you shouldn't be able to see it

2022-10-10 13:52 UTC, mwalbeck requested changes

2022-10-10 13:52 UTC, mwalbeck commented on appinfo/info.xml
> +	<version>102.11.2</version>
Can you change the version number to `100.6.0-alpha.1` as then we have the version numbering synced between the various apps.

And if you note the upstream version in the readme, so we also have an easy place to find it.

2022-10-10 15:38 UTC, oliveiraigorm commented on appinfo/info.xml
> +	<version>102.11.2</version>
The upstream version is already set on the readme on main

2022-10-11 12:06 UTC, mwalbeck commented on appinfo/info.xml
> +	<version>102.11.2</version>
Perfect!

2022-10-11 12:06 UTC, mwalbeck approved these changes

2022-10-11 12:06 UTC, merged